/*DATAMIGRATION 69E596A8-B771-441F-881F-0C63E19E3A1C*/ -- Change the script's code only if it needs to be executed again.

-- The following lines are generated by: EXEC Rhetos.HelpDataMigration '_Models', 'Subject';
EXEC Rhetos.DataMigrationUse 'Models', 'Subject', 'ID', 'uniqueidentifier';
EXEC Rhetos.DataMigrationUse 'Models', 'Subject', 'Title', 'nvarchar(256)';
EXEC Rhetos.DataMigrationUse 'Models', 'Subject', 'ActiveSince', 'datetime2(3)';
EXEC Rhetos.DataMigrationUse 'Models', 'Subject', 'Active', 'bit';
GO

-- ... write the data migration queries here (don't forget to use the underscore '_' in schema name) ...
INSERT INTO _Models.Subject (ID, Title, Active) VALUES (NEWID(), 'Hrvatski jezik', 1);
INSERT INTO _Models.Subject (ID, Title, Active) VALUES (NEWID(), 'Likovna kultura', 1);
INSERT INTO _Models.Subject (ID, Title, Active) VALUES (NEWID(), 'Glazbena kultura', 1);
INSERT INTO _Models.Subject (ID, Title, Active) VALUES (NEWID(), 'Matematika', 1);
INSERT INTO _Models.Subject (ID, Title, Active) VALUES (NEWID(), 'Priroda', 1);
INSERT INTO _Models.Subject (ID, Title, Active) VALUES (NEWID(), 'Biologija', 1);
INSERT INTO _Models.Subject (ID, Title, Active) VALUES (NEWID(), 'Kemija', 1);
INSERT INTO _Models.Subject (ID, Title, Active) VALUES (NEWID(), 'Fizika', 1);
INSERT INTO _Models.Subject (ID, Title, Active) VALUES (NEWID(), 'Priroda i društvo', 1);
INSERT INTO _Models.Subject (ID, Title, Active) VALUES (NEWID(), 'Povijest', 1);
INSERT INTO _Models.Subject (ID, Title, Active) VALUES (NEWID(), 'Geografija', 1);
INSERT INTO _Models.Subject (ID, Title, Active) VALUES (NEWID(), 'Tehnička kultura', 1);
INSERT INTO _Models.Subject (ID, Title, Active) VALUES (NEWID(), 'Tjelesna i zdrastvena kultura', 1);
INSERT INTO _Models.Subject (ID, Title, Active) VALUES (NEWID(), 'Vjeronauk', 1);
INSERT INTO _Models.Subject (ID, Title, Active) VALUES (NEWID(), 'Informatika', 1);
INSERT INTO _Models.Subject (ID, Title, Active) VALUES (NEWID(), 'Engleski jezik', 1);
INSERT INTO _Models.Subject (ID, Title, Active) VALUES (NEWID(), 'Njemački jezik', 1);

EXEC Rhetos.DataMigrationApplyMultiple 'Models', 'Subject', 'ID, Title, ActiveSince, Active';