/*DATAMIGRATION 9651A7C2-0923-4813-AD25-FFD574BA967F*/ -- Change the script's code only if it needs to be executed again.

-- The following lines are generated by: EXEC Rhetos.HelpDataMigration 'Models', 'DisabilityType';
EXEC Rhetos.DataMigrationUse 'Models', 'DisabilityType', 'ID', 'uniqueidentifier';
EXEC Rhetos.DataMigrationUse 'Models', 'DisabilityType', 'Type', 'nvarchar(256)';
EXEC Rhetos.DataMigrationUse 'Models', 'DisabilityType', 'ActiveSince', 'datetime2(3)';
EXEC Rhetos.DataMigrationUse 'Models', 'DisabilityType', 'Active', 'bit';
EXEC Rhetos.DataMigrationUse 'Models', 'DisabilitySubtype', 'ID', 'uniqueidentifier';
EXEC Rhetos.DataMigrationUse 'Models', 'DisabilitySubtype', 'Subtype', 'nvarchar(MAX)';
EXEC Rhetos.DataMigrationUse 'Models', 'DisabilitySubtype', 'ActiveSince', 'datetime2(3)';
EXEC Rhetos.DataMigrationUse 'Models', 'DisabilitySubtype', 'DisabilityTypeID', 'uniqueidentifier';
EXEC Rhetos.DataMigrationUse 'Models', 'DisabilitySubtype', 'Active', 'bit';
GO

-- ... write the data migration queries here (don't forget to use the underscore '_' in schema name) ...
DECLARE  
	@OstecenjaVidaID UNIQUEIDENTIFIER = '8E54A761-E4E5-4F2E-A6E5-9190C03BD540',  
	@OstecenjaSluhaID UNIQUEIDENTIFIER ='35C99A8F-7D80-4B86-8BF5-0BFFF0C84029', 
	@OstecenjaJezicnoGovorneGlasovneKomunikacijeISpecificneTeskoceID UNIQUEIDENTIFIER = '26CF4F96-A09B-4EFE-9806-C6CB98A8EE15',
	@OstecenjaOrganaIOrganskihSustavaID UNIQUEIDENTIFIER = '233441EF-0F1B-4F09-9661-D86604744C5B',
	@IntelektualneTeskoceID UNIQUEIDENTIFIER = 'D84A830E-B3A3-42E3-84E8-7B1F9229FBD4',
	@PoremecajiUPonasanjuIOstecenjaMentalnogZdravljaID UNIQUEIDENTIFIER = 'D7B27BB5-B1E1-4553-B670-D1B28FD811AD'

INSERT INTO _Models.DisabilityType (ID, Type, Active) VALUES (@OstecenjaVidaID, 'Oštećenja vida', 1);
INSERT INTO _Models.DisabilityType (ID, Type, Active) VALUES (@OstecenjaSluhaID, 'Oštećenja sluha', 1);
INSERT INTO _Models.DisabilityType (ID, Type, Active) VALUES (@OstecenjaJezicnoGovorneGlasovneKomunikacijeISpecificneTeskoceID, 'Oštećenja jezično-govorne-glasovne komunikacije i specifične teškoće u učenju', 1);
INSERT INTO _Models.DisabilityType (ID, Type, Active) VALUES (@OstecenjaOrganaIOrganskihSustavaID, 'Oštećenja organa i organskih sustava', 1);
INSERT INTO _Models.DisabilityType (ID, Type, Active) VALUES (@IntelektualneTeskoceID, 'Intelektualne teškoće', 1);
INSERT INTO _Models.DisabilityType (ID, Type, Active) VALUES (@PoremecajiUPonasanjuIOstecenjaMentalnogZdravljaID, 'Poremećaji u ponašanju i oštećenja mentalnog zdravlja', 1);

INSERT INTO _Models.DisabilitySubtype (ID, Subtype, DisabilityTypeID, Active) VALUES (NEWID(), 'sljepoća', @OstecenjaVidaID, 1);
INSERT INTO _Models.DisabilitySubtype (ID, Subtype, DisabilityTypeID, Active) VALUES (NEWID(), 'slabovidnost', @OstecenjaVidaID, 1);

-- Oštećenja sluha
INSERT INTO _Models.DisabilitySubtype (ID, Subtype, DisabilityTypeID, Active) VALUES (NEWID(), 'gluhoća', @OstecenjaSluhaID, 1);
INSERT INTO _Models.DisabilitySubtype (ID, Subtype, DisabilityTypeID, Active) VALUES (NEWID(), 'nagluhost', @OstecenjaSluhaID, 1);

-- Oštećenja jezično-govorne glasovne komunikacije i specifične teškoće u učenju
INSERT INTO _Models.DisabilitySubtype (ID, Subtype, DisabilityTypeID, Active) VALUES (NEWID(), 'poremećaji glasa', @OstecenjaJezicnoGovorneGlasovneKomunikacijeISpecificneTeskoceID, 1);
INSERT INTO _Models.DisabilitySubtype (ID, Subtype, DisabilityTypeID, Active) VALUES (NEWID(), 'jezične teškoće', @OstecenjaJezicnoGovorneGlasovneKomunikacijeISpecificneTeskoceID, 1);
INSERT INTO _Models.DisabilitySubtype (ID, Subtype, DisabilityTypeID, Active) VALUES (NEWID(), 'poremećaji govora', @OstecenjaJezicnoGovorneGlasovneKomunikacijeISpecificneTeskoceID, 1);
INSERT INTO _Models.DisabilitySubtype (ID, Subtype, DisabilityTypeID, Active) VALUES (NEWID(), 'komunikacijske teškoće', @OstecenjaJezicnoGovorneGlasovneKomunikacijeISpecificneTeskoceID, 1);
INSERT INTO _Models.DisabilitySubtype (ID, Subtype, DisabilityTypeID, Active) VALUES (NEWID(), 'specifične teškoće u učenju', @OstecenjaJezicnoGovorneGlasovneKomunikacijeISpecificneTeskoceID, 1);

-- Oštećenja organa i organskih sustava
INSERT INTO _Models.DisabilitySubtype (ID, Subtype, DisabilityTypeID, Active) VALUES (NEWID(), 'oštećenja mišićno-koštanoga sustava', @OstecenjaOrganaIOrganskihSustavaID, 1);
INSERT INTO _Models.DisabilitySubtype (ID, Subtype, DisabilityTypeID, Active) VALUES (NEWID(), 'oštećenja središnjega živčanog sustava', @OstecenjaOrganaIOrganskihSustavaID, 1);
INSERT INTO _Models.DisabilitySubtype (ID, Subtype, DisabilityTypeID, Active) VALUES (NEWID(), 'oštećenja perifernoga živčanog sustava', @OstecenjaOrganaIOrganskihSustavaID, 1);
INSERT INTO _Models.DisabilitySubtype (ID, Subtype, DisabilityTypeID, Active) VALUES (NEWID(), 'oštećenja drugih sustava (dišni, srčanožilni, probavni, endokrini, koža i potkožna tkiva, mokraćni, spolni)', @OstecenjaOrganaIOrganskihSustavaID, 1);

-- Intelektualne teškoće
INSERT INTO _Models.DisabilitySubtype (ID, Subtype, DisabilityTypeID, Active) VALUES (NEWID(), 'Laka intelektualna teškoća zbog koje treba, radi postizanja odgovarajućega socijalnog funkcioniranja, osigurati primjerene uvjete za osposobljavanje (kvocijent inteligencije približno je u rasponu od 50 do 69)', @IntelektualneTeskoceID, 1);
INSERT INTO _Models.DisabilitySubtype (ID, Subtype, DisabilityTypeID, Active) VALUES (NEWID(), 'Umjerena intelektualna teškoća zbog koje treba, radi postizanja djelomičnoga socijalnog funkcioniranja, osigurati primjerene uvjete za osposobljavanje u zadovoljavanju jednostavnih radnih aktivnosti (kvocijent inteligencije približno se kreće u rasponu od 35 do 49)', @IntelektualneTeskoceID, 1);
INSERT INTO _Models.DisabilitySubtype (ID, Subtype, DisabilityTypeID, Active) VALUES (NEWID(), 'Teža intelektualna teškoća zbog koje treba, radi zadovoljavanja najjednostavnijih osnovnih osobnih potreba, komuniciranja s okolinom i obavljanja najjednostavnijih radnih aktivnosti, osigurati primjerene uvjete za rehabilitaciju, njegu i pomoć (kvocijent inteligencije približno se kreće u rasponu od 20 do 34)', @IntelektualneTeskoceID, 1);
INSERT INTO _Models.DisabilitySubtype (ID, Subtype, DisabilityTypeID, Active) VALUES (NEWID(), 'Teška intelektualna teškoća zbog koje treba, radi zadovoljavanja najjednostavnijih osnovnih osobnih potreba, komuniciranja s okolinom i obavljanja najjednostavnijih radnih aktivnosti, osigurati primjerene uvjete za rehabilitaciju, njegu i pomoć (kvocijent inteligencije približno se kreće u rasponu od 0 do 19)', @IntelektualneTeskoceID, 1);

-- Poremećaji u ponašanju i oštećenja mentalnog zdravlja
INSERT INTO _Models.DisabilitySubtype (ID, Subtype, DisabilityTypeID, Active) VALUES (NEWID(), 'Organski, uključujući simptomatski mentalni poremećaj', @PoremecajiUPonasanjuIOstecenjaMentalnogZdravljaID, 1);
INSERT INTO _Models.DisabilitySubtype (ID, Subtype, DisabilityTypeID, Active) VALUES (NEWID(), 'Poremećaji raspoloženja', @PoremecajiUPonasanjuIOstecenjaMentalnogZdravljaID, 1);
INSERT INTO _Models.DisabilitySubtype (ID, Subtype, DisabilityTypeID, Active) VALUES (NEWID(), 'Neurotski poremećaji, poremećaji vezani uz stres i somatoformni', @PoremecajiUPonasanjuIOstecenjaMentalnogZdravljaID, 1);
INSERT INTO _Models.DisabilitySubtype (ID, Subtype, DisabilityTypeID, Active) VALUES (NEWID(), 'Shizofrenija, shizotipni i sumanuti poremećaji', @PoremecajiUPonasanjuIOstecenjaMentalnogZdravljaID, 1);
INSERT INTO _Models.DisabilitySubtype (ID, Subtype, DisabilityTypeID, Active) VALUES (NEWID(), 'Poremećaji iz autističnoga spektra', @PoremecajiUPonasanjuIOstecenjaMentalnogZdravljaID, 1);
INSERT INTO _Models.DisabilitySubtype (ID, Subtype, DisabilityTypeID, Active) VALUES (NEWID(), 'Poremećaji aktivnosti i pažnje', @PoremecajiUPonasanjuIOstecenjaMentalnogZdravljaID, 1);
INSERT INTO _Models.DisabilitySubtype (ID, Subtype, DisabilityTypeID, Active) VALUES (NEWID(), 'Poremećaji u ponašanju i osjećanju', @PoremecajiUPonasanjuIOstecenjaMentalnogZdravljaID, 1);


EXEC Rhetos.DataMigrationApplyMultiple 'Models', 'DisabilityType', 'ID, Type, ActiveSince, Active';
EXEC Rhetos.DataMigrationApplyMultiple 'Models', 'DisabilitySubtype', 'ID, Subtype, ActiveSince, DisabilityTypeID, Active';
