/*DATAMIGRATION 93021739-4E24-428D-88B2-851821FAAA7A*/ -- Change the script's code only if it needs to be executed again.

-- The following lines are generated by: EXEC Rhetos.HelpDataMigration 'Models', 'EducationLocation';
EXEC Rhetos.DataMigrationUse 'Models', 'EducationLocation', 'ID', 'uniqueidentifier';
EXEC Rhetos.DataMigrationUse 'Models', 'EducationLocation', 'Location', 'nvarchar(256)';
EXEC Rhetos.DataMigrationUse 'Models', 'EducationLocation', 'ActiveSince', 'datetime2(3)';
EXEC Rhetos.DataMigrationUse 'Models', 'EducationLocation', 'Active', 'bit';
GO

-- ... write the data migration queries here (don't forget to use the underscore '_' in schema name) ...
INSERT INTO _Models.EducationLocation (ID, Location, Active) VALUES (NEWID(), 'u redovitome razrednom odjelu', 1);
INSERT INTO _Models.EducationLocation (ID, Location, Active) VALUES (NEWID(), 'dijelom u redovitome, a dijelom u posebnome razrednom odjelu', 1);
INSERT INTO _Models.EducationLocation (ID, Location, Active) VALUES (NEWID(), 'u posebnome razrednom odjelu', 1);
INSERT INTO _Models.EducationLocation (ID, Location, Active) VALUES (NEWID(), 'u odgojno-obrazovnoj skupini', 1);

EXEC Rhetos.DataMigrationApplyMultiple 'Models', 'EducationLocation', 'ID, Location, ActiveSince, Active';