/*DATAMIGRATION C82D467C-2511-424D-931D-BEF0E81C95AC*/ -- Change the script's code only if it needs to be executed again.

-- The following lines are generated by: EXEC Rhetos.HelpDataMigration 'Models', 'EducationType';
EXEC Rhetos.DataMigrationUse 'Models', 'EducationType', 'ID', 'uniqueidentifier';
EXEC Rhetos.DataMigrationUse 'Models', 'EducationType', 'Type', 'nvarchar(256)';
EXEC Rhetos.DataMigrationUse 'Models', 'EducationType', 'ActiveSince', 'datetime2(3)';
EXEC Rhetos.DataMigrationUse 'Models', 'EducationType', 'Active', 'bit';
GO

-- ... write the data migration queries here (don't forget to use the underscore '_' in schema name) ...
INSERT INTO _Models.EducationType (ID, Type, Active) VALUES (NEWID(), 'redoviti program uz individualizirane postupke', 1);
INSERT INTO _Models.EducationType (ID, Type, Active) VALUES (NEWID(), 'redoviti program uz prilagodbu sadržaja i individualizirane postupke', 1);
INSERT INTO _Models.EducationType (ID, Type, Active) VALUES (NEWID(), 'posebni program uz individualizirane postupke', 1);
INSERT INTO _Models.EducationType (ID, Type, Active) VALUES (NEWID(), 'posebni programi za stjecanje kompetencija u aktivnostima svakodnevnoga života i rada uz individualizirane postupke', 1);



EXEC Rhetos.DataMigrationApplyMultiple 'Models', 'EducationType', 'ID, Type, ActiveSince, Active';